### ISSUE TITLE
HTML Layouts

### ISSUE THREAD

**Issue by Jpeyton-hub** [Jpeyton-hub/Barkle#4]
rough out an idea of how we would like the page to actually look...

**Comment by Jpeyton-hub** [comment]
Hey Brandon, I was just looking through the api-routes folder and the routes are set-up to reflect a login page which can have a link to a user creation page (labeled sign-up). I think the sign-up.html page you've created looks great but I think it should be our login.html and then we can make the signup.html contain the form for actual user creation.

**Comment by bash7325** [comment]
I noticed that late last night too, I'll split these up today.  Thanks!
